{% set name = "emcee" %}
{% set version = "3.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/emcee-{{ version }}.tar.gz
  sha256: 8e0e19dc8bcef9c6d02f860bef8ddc6c876b8878a6ce666943e2c5cfd9317fed

build:
  number: 1
  skip: True  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - setuptools >=40.6.0
    - setuptools-scm
    - wheel
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - emcee
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -v --pyargs emcee
    # skip test_indexing on osx-64 because numpy version
    # 'numpy.testing.assert_allclose' introduced in numpy 1.5
    - pytest -v --pyargs emcee -k "not test_indexing"  # [osx and x86_64]

about:
  home: https://emcee.readthedocs.io
  summary: The Python ensemble sampling toolkit for MCMC
  description: |
    emcee is a stable, well tested Python implementation of the
    affine-invariant ensemble sampler for Markov chain Monte Carlo (MCMC)
    proposed by Goodman & Weare (2010).
  license: MIT
  license_file: LICENSE
  license_family: MIT
  dev_url: https://github.com/dfm/emcee
  doc_url: https://emcee.readthedocs.io

extra:
  recipe-maintainers:
    - ericdill
    - tacaswell
    - licode
    - dfm
    - danielballan
