{% set version = "3.1.1" %}

package:
  name: emcee
  version: {{ version }}

source:
  fn: emcee-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/e/emcee/emcee-{{ version }}.tar.gz
  sha256: 48ffc6a7f5c51760b7a836056184c7286a9959ef81b45b977b02794f1210fb5c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - numpy

  run:
    - python >=3.6
    - numpy
    - tqdm
    - h5py
    - schwimmbad

test:
  imports:
    - emcee

about:
  home: https://emcee.readthedocs.io
  license: MIT
  license_file: LICENSE
  summary: The Python ensemble sampling toolkit for affine-invariant MCMC

extra:
  recipe-maintainers:
    - ericdill
    - tacaswell
    - licode
    - dfm
    - danielballan
