{% set version = "2.2.1" %}

package:
  name: emcee
  version: {{ version }}

source:
  fn: emcee-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/e/emcee/emcee-{{ version }}.tar.gz
  md5: cd3f7a6ff6a8124fed86afeea69b9cac

build:
  number: 2
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy

test:
  imports:
    - emcee

about:
  home: http://dan.iel.fm/emcee/
  license: MIT
  summary: 'Kick ass affine-invariant ensemble MCMC sampling'

extra:
  recipe-maintainers:
    - ericdill
    - tacaswell
    - licode
    - dfm
    - danielballan
