{% set version = "3.0.1" %}

package:
  name: emcee
  version: {{ version }}

source:
  fn: emcee-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/e/emcee/emcee-{{ version }}.tar.gz
  sha256: 2c7929f7dacfd9bcd320d590c51fb5cfd8a46882349e3c5412b7c8a3080fbd06

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy
    - tqdm
    - h5py
    - schwimmbad

test:
  imports:
    - emcee

about:
  home: https://emcee.readthedocs.io
  license: MIT
  license_file: LICENSE
  summary: 'The Python ensemble sampling toolkit for affine-invariant MCMC'

extra:
  recipe-maintainers:
    - ericdill
    - tacaswell
    - licode
    - dfm
    - danielballan
