{% set name = "emcee" %}
{% set version = "3.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/emcee-{{ version }}.tar.gz
  sha256: fb6865b38a3f03402b79e0d90685ecb87c4124dd6e7eb41555ba7a6d094fcad0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=40.6.0
    - setuptools-scm
    - wheel
  run:
    - numpy
    - python >=3.6

test:
  imports:
    - emcee
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://emcee.readthedocs.io
  summary: The Python ensemble sampling toolkit for MCMC
  dev_url: https://github.com/dfm/emcee
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ericdill
    - tacaswell
    - licode
    - dfm
    - danielballan
