travis:
  secure:
    BINSTAR_TOKEN: KP3xkARojr3HAP7BuF6XTy3AZeqg4br9AK5cg/K/nHp/pUFndBYaRXQT9q5MQa0o1OgNIBHEEgm7hiT+mpnqiHXYfRAS5J10pdCCXyzKC4FZcG1n+DyR7EFWSbK8ikIPfm4jALq3z/lybXR+TIGGhZ2STLvDqF8tOIVWyJjbkJtXdoZwlbGTcCH27FlIuHW9VLZPcCXdI3pZc0lV2sKJ+96P4tNi3uOgvoIlafLc41/AiqLnXfWuz3raiyt47F29Uri5aMBf/UerKbY4V2/JMc+oqqAZupFOJC9Nm8tyeTuwjuqq80ASVrL9TFFwupdEmHmXUPlhAXzZAYnp2nD5P/ABMQL9nOx9Q5HH9eMcz2SapnI1iaeo16LLyqcrE8iXhrhmHWgUZ3z7yX8J7BDtHbtOQmykwu0Xk/QYLQxstO8vBeoRG0gUiLlI0TJuSLXDPdfyjR5VXetC8r8GvblEiyPOeRkV8fZdafZiF+EGpeK9MnnPrqN+VtLRVVudle17LdngF/BKjf/ksTHqPhcz1lknyOhaobIMeeUORbysmuKMJ0U/OrT1RAOWnkc3nEWCY2zBzviejVLDgD5VUfBgsSnSu0WzrDU7VX4CtwwVn6z//VZkL6r/fG5CIiB3iaRHPLOUtKWCmB/nzWsps0X8n5A4qOdbaytl5st/ZIAQUWA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
