travis:
  secure:
    BINSTAR_TOKEN: pcqjMNmqaKhBJ/83I1Sszb17vcmS2LR7bATYdn7nfpXC+iXeqtXcIpBfthCpHDFvb4WW8+Ovp1e1uCXWXnlac2efzbnQYYeruDsXrbBJhVn+ZkT5dqmJ38+Ydu+8xoiQSrBUSjGmPWH3eCRkUHSFrBlK682BBCM+dKCe93kZdyxKec5TQyNh+Pm9te9B/74XIxkZtdIPT72/7PEw3qOiskeQI8cjtFZBd7WF+TekIZOeIae9I3PUm3LDgw6mcjS84rL+bOEWw3FP9EtSMWR83q+x0Mv2fQeN33GEf3zrqN96Qa59qRuSeUFIyMCW14iu0LrHeTgoD/GUEsD/YH+PLsVu7VPmmnTCHSO9f60jMNrPfZlXHgc/DKTu+cDjcN8sytvnCpSYql1BBpqrXU03VC22Qr+83Q4C8bgeW9dvzxJeGABebgOR39YxlEEuD1yFG7V+FsDDLOUYxhATrHjgTGP55iSZYUPt0D1HpDRNB7CGBmuya9ZNj/F5w6uWsVcd9n3hlhWD30N6uOpG85yyLp5YIlSScx5I33LOSqbPr/uUnOuS56lerJd7KoGgDEptIL2ZNxDKWVS6leTGluAUKTPEPQ66WOaR4zttQAzkWagpc9AD9GtfvXmrs3RMxvlrl4p0Bp0MvsOwEaCNjulSkuohaN5SM8FNFwzUxHTuI8c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
